# Generated by Django 5.2.1 on 2025-05-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image to include in your post",
                null=True,
                upload_to="post_images/",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(help_text="You can use Markdown formatting"),
        ),
    ]
