# Generated by Django 5.2.1 on 2025-05-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
