# Generated by Django 5.2.1 on 2025-05-29 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_post_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("unique_visitors", models.IntegerField(default=0)),
                ("unique_reads", models.IntegerField(default=0)),
                ("total_views", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Daily analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=500)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.CharField(blank=True, max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("session_key", models.CharField(blank=True, max_length=40)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="core.post",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="core_pagevi_timesta_4fa7e6_idx"
                    ),
                    models.Index(
                        fields=["post", "-timestamp"],
                        name="core_pagevi_post_id_8b2170_idx",
                    ),
                    models.Index(
                        fields=["session_key", "-timestamp"],
                        name="core_pagevi_session_5db8a1_idx",
                    ),
                ],
            },
        ),
    ]
